// Generated by CoffeeScript 1.4.0

define({
  events: {
    'this#grid:onSelectRow': 'selectChanged'
  },
  model: function() {
    return this.feature.startupOptions.model;
  },
  components: [
    function() {
      return {
        type: 'grid',
        selector: 'grid',
        pager: 'pager',
        colModel: this.feature.startupOptions.colModel
      };
    }
  ]
});
