// Generated by CoffeeScript 1.4.0
(function() {

  define(["jquery"], function($) {
    var getFormData;
    getFormData = function(view) {
      var data, values;
      values = view.$$("form").serializeArray();
      data = {};
      return _(values).map(function(item) {
        if (item.name in data) {
          if (_.isArray(data[item.name])) {
            data[item.name] = data[item.name].concat([item.value]);
          } else {
            data[item.name] = [data[item.name], item.value];
          }
        } else {
          data[item.name] = item.value;
        }
        view.model.set(data);
        return _(view.components).each(function(component) {
          var d;
          if (_.isFunction(component.getFormData)) {
            d = component.getFormData();
            if (d) {
              return view.model.set(d.name, d.value);
            }
          }
        });
      });
    };
    return {
      audit: function() {
        var app, grid, me, ogrid, selected;
        me = this;
        grid = me.feature.views["grid"].components[0];
        ogrid = me.feature.views["completed-grid"].components[0];
        selected = grid.getGridParam("selrow");
        app = me.feature.module.getApplication().applicationRoot;
        if (!selected) {
          return app.info("请选择要操作的记录");
        }
        me.feature.model.set("id", selected);
        $.when(me.feature.model.fetch()).done(function() {
          return app.loadView(me.feature, "forms:" + selected).done(function(view) {
            return app.showDialog({
              view: view,
              title: "Task Process",
              buttons: [
                {
                  label: "Finish",
                  fn: function() {
                    var valid;
                    getFormData(view);
                    valid = view.$$("form").valid();
                    if (!valid) {
                      return false;
                    }
                    view.model.set("id", selected);
                    view.model.save().done(function() {
                      grid.trigger("reloadGrid");
                      return ogrid.trigger("reloadGrid");
                    });
                    return true;
                  }
                }, {
                  label: "Reject",
                  fn: function() {
                    return me.feature.request({
                      url: "reject/" + selected
                    }).done(function() {
                      return grid.trigger("reloadGrid");
                    });
                  }
                }
              ]
            });
          });
        });
        return true;
      }
    };
  });

}).call(this);
