// Generated by CoffeeScript 1.8.0

/* 
 * @require jquery
 * @require bootstrap
 * @require underscore
 * @require backbone
 * @require react
 */
var v;

v = window.v = {};

v.$ = $;

v._ = _;

v.b = Backbone;

v.r = React;

delete $;

delete _;

delete Backbone;

delete React;
