// Generated by CoffeeScript 1.4.0
(function() {

  define(function() {
    var sortable;
    sortable = {
      id: true,
      processInstanceId: true,
      processDefinitionId: true,
      startTime: true,
      endTime: true,
      durationInMillis: true,
      deleteReason: true,
      endActivityId: true,
      businessKey: true,
      startUserId: true,
      startActivityId: true,
      superProcessInstanceId: true
    };
    return {
      path: "completed",
      components: [
        function() {
          var c, o, _i, _len, _ref, _ref1;
          o = {
            type: "grid",
            selector: "grid",
            pager: "pager",
            fit: true,
            colModel: [
              {
                name: "id",
                label: "ID"
              }, {
                name: "name",
                label: "Name"
              }, {
                name: "createTime",
                label: "Create Time"
              }, {
                name: 'durationInMillis'
              }
            ]
          };
          if ((_ref = this.feature.startupOptions.option) != null ? _ref.finishedColModel : void 0) {
            o.colModel = this.feature.startupOptions.option.finishedColModel;
          }
          _ref1 = o.colModel;
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            c = _ref1[_i];
            c.sortable = !!sortable[c.name];
          }
          return o;
        }
      ],
      avoidLoadingHandlers: true,
      avoidLoadingModel: true
    };
  });

}).call(this);
