// Generated by CoffeeScript 1.4.0
(function() {

  define(function() {
    var sortable;
    sortable = {
      id: true,
      name: true,
      description: true,
      priority: true,
      owner: true,
      assignee: true,
      processInstanceId: true,
      processDefinitionId: true,
      createTime: true,
      dueDate: true,
      startTime: true,
      endTime: true
    };
    return {
      components: [
        function() {
          var c, o, _i, _len, _ref, _ref1;
          o = {
            type: "grid",
            selector: "grid",
            pager: "pager",
            multiselect: true,
            colModel: [
              {
                name: "id",
                label: "ID"
              }, {
                name: "name",
                label: "Name"
              }, {
                name: "createTime",
                label: "Create Time"
              }, {
                name: "assignee",
                label: "Assignee"
              }
            ]
          };
          if ((_ref = this.feature.startupOptions.option) != null ? _ref.toDoColModel : void 0) {
            o.colModel = this.feature.startupOptions.option.toDoColModel;
          }
          _ref1 = o.colModel;
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            c = _ref1[_i];
            c.sortable = !!sortable[c.name];
          }
          return o;
        }
      ],
      avoidLoadingHandlers: true
    };
  });

}).call(this);
