// Generated by CoffeeScript 1.4.0
(function() {

  define({
    resizeToFit: function($grid) {
      var $bdiv, $header, $parent, marginTop, targetHeight;
      $parent = $grid.closest('.ui-jqgrid').parent();
      marginTop = parseInt($parent.css('margin-top'));
      targetHeight = $parent.height() - marginTop;
      $bdiv = $grid.parents('.ui-jqgrid-bdiv');
      $header = $bdiv.prev();
      $grid.jqGrid('setGridHeight', targetHeight - $header.height() - 10);
      return $grid.jqGrid('setGridWidth', $parent.width());
    },
    onLayoutResize: function(x, ui) {
      var $ui, me;
      me = this;
      $ui = ui.jquery ? ui : $(ui.panel);
      return $ui.filter(':visible').find('.ui-jqgrid-fit:visible').each(function() {
        var $grid;
        $grid = $(this);
        return me.resizeToFit($grid, $ui);
      });
    }
  });

}).call(this);
