// Generated by CoffeeScript 1.4.0
(function() {

  define(['coala/core/loader-plugin-manager', 'coala/scaffold/forms-view-loader', 'coala/scaffold/notfound-feature-loader', 'coala/scaffold/views-view-loader', 'coala/scaffold/tree-views-view-loader', 'coala/scaffold/treetable-views-view-loader', 'coala/components/layout', 'coala/components/grid', 'coala/components/accordion', 'coala/components/tree', 'coala/components/select', 'coala/components/picker', 'coala/components/tabs', 'coala/components/datetimepicker', 'coala/vendors/jquery/jquery.validate', 'coala/features/grid-picker', 'coala/features/tree-picker', 'coala/features/pick-to-grid', 'coala/features/tasks'], function(LoaderPluginManager, formsLoader, notFoundFeatureLoader, viewsLoader, treeViewsLoader, treeTableViewsLoader) {
    LoaderPluginManager.register(formsLoader);
    LoaderPluginManager.register(notFoundFeatureLoader);
    LoaderPluginManager.register(viewsLoader);
    LoaderPluginManager.register(treeViewsLoader);
    return LoaderPluginManager.register(treeTableViewsLoader);
  });

}).call(this);
