// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  define(['jquery', 'underscore', 'backbone', 'marionette', 'handlebars', 'coala/core/config', 'coala/core/util', 'coala/core/resource-loader', 'coala/core/loader-plugin-manager'], function($, _, Backbone, Marionette, Handlebars, config, util, loadResource, loaderPluginManager) {
    var Application, error, log;
    log = util.log, error = util.error;
    return Application = (function(_super) {

      __extends(Application, _super);

      function Application(options) {
        this.options = options;
        this.baseName = config.applicationName;
        this.paths = [config.applicationName];
        this.parent = null;
        this.features = {};
        Application.__super__.constructor.apply(this, arguments);
        this.promises = [];
        this.initRouters();
      }

      Application.prototype.getPromises = function() {
        return this.getApplication().promises;
      };

      Application.prototype.addPromise = function(promise) {
        var idx, promises;
        promises = this.getPromises();
        idx = promises.length;
        promises.push(promise);
        return idx;
      };

      Application.prototype.done = function(fn) {
        return $.when.apply($, this.getPromises()).done(fn);
      };

      Application.prototype.initRouters = function() {
        var idx;
        idx = this.addPromise(this.loadResource(config.routerFileName));
        return this.done(_.bind(function() {
          var Router, args, def, index, name, nrs, routes, value;
          index = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
          def = args[index];
          if (!def) {
            return;
          }
          def = _.extend({}, def);
          nrs = {};
          routes = def.routes;
          for (name in routes) {
            value = routes[name];
            nrs[this.path(name, true)] = value;
          }
          def.routes = nrs;
          def.module = this;
          Router = Backbone.Router.extend(def);
          return this.router = new Router();
        }, this, idx));
      };

      Application.prototype.path = function(append, withoutRoot) {
        var paths;
        paths = withoutRoot === true ? this.paths.slice(1) : this.paths;
        append = _.isArray(append) ? append : [append];
        paths = paths.concat(append);
        return paths.join('/');
      };

      Application.prototype.url = function(append) {
        var path, prefix;
        prefix = config.urlPrefix;
        prefix = _.isFunction(prefix) ? prefix(this) : prefix;
        path = prefix + '/' + this.path(null, true);
        if (append) {
          path += '/' + append;
        }
        return path.replace(/\/{2,}/g, '/');
      };

      Application.prototype.module = function(names) {
        var module, name, parent, ps, _i, _len;
        names = _.isArray(names) ? names : names.split('/');
        parent = this;
        for (_i = 0, _len = names.length; _i < _len; _i++) {
          name = names[_i];
          ps = [].concat(parent.paths);
          ps.push(name);
          module = parent[name] || (parent[name] = new Application({
            baseName: name,
            parent: parent,
            paths: ps
          }));
          parent = module;
        }
        return parent;
      };

      Application.prototype.getApplication = function() {
        var root;
        if (!this.root) {
          root = this;
          while (root.parent !== null) {
            root = root.parent;
          }
          this.root = root;
        }
        return this.root;
      };

      Application.prototype.findModule = function(names) {
        var module, name, _i, _len;
        names = _.isArray(names) ? names : names.split('/');
        module = this;
        for (_i = 0, _len = names.length; _i < _len; _i++) {
          name = names[_i];
          module = module != null ? module[name] : void 0;
        }
        return module;
      };

      Application.prototype.findFeature = function(name) {
        var cid, feature, _ref;
        _ref = this.features;
        for (cid in _ref) {
          feature = _ref[cid];
          if (feature.baseName === name) {
            return feature;
          }
        }
      };

      Application.prototype.resolveResoucePath = function(resourcePath) {
        if (resourcePath.charAt(0) === '/') {
          return this.getApplication().path(resourcePath.substring(1));
        }
        return this.path(resourcePath);
      };

      Application.prototype.loadResource = function(resourcePath, plugin, useOrginalPath) {
        var path;
        if (useOrginalPath === true) {
          return loadResource(resourcePath, plugin);
        }
        if (resourcePath.charAt(0) === '/') {
          return this.getApplication().loadResource(resourcePath.substring(1));
        }
        path = this.resolveResoucePath(resourcePath);
        return loadResource(path, plugin);
      };

      Application.prototype.startFeature = function(featurePath, options) {
        var deferred, f, featureName, ignoreExists, module, names, _i, _ref;
        _ref = featurePath.split('/'), names = 2 <= _ref.length ? __slice.call(_ref, 0, _i = _ref.length - 1) : (_i = 0, []), featureName = _ref[_i++];
        module = this.findModule(names) || this.module(names);
        f = module.findFeature(featureName);
        ignoreExists = (f != null ? f.ignoreExists : void 0) || (options != null ? options.ignoreExists : void 0);
        if (f && ignoreExists !== true) {
          return f.activate(options);
        }
        deferred = $.Deferred();
        module.addPromise(deferred);
        $.when(loaderPluginManager.invoke('feature', module, null, featureName, options)).then(function(feature) {
          if (feature === null) {
            log(module, "feature not found with path: " + featurePath);
            deferred.resolve(null);
            return module.startFeature('notfound:' + featureName, options);
          }
          module.features[feature.cid] = feature;
          return feature.start().done(function() {
            return deferred.resolve(feature);
          });
        });
        return deferred;
      };

      Application.prototype.stopFeature = function(feature) {
        feature.stop();
        return delete feature.module.features[feature.cid];
      };

      return Application;

    })(Marionette.Application);
  });

}).call(this);
