// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  define(['marionette', 'jquery', 'underscore', 'coala/core/config', 'coala/core/component-handler', 'coala/core/util'], function(Marionette, $, _, config, ComponentHandler, util) {
    var BaseView, error, getPath;
    getPath = config.getPath;
    error = util.error;
    BaseView = (function(_super) {

      __extends(BaseView, _super);

      function BaseView(options) {
        var key, old, value, _ref;
        this.options = options;
        this.promises || (this.promises = []);
        this.module = options.module;
        this.feature = options.feature;
        this.baseName = options.baseName;
        if (options.extend) {
          _ref = options.extend;
          for (key in _ref) {
            value = _ref[key];
            old = this[key];
            if (_.isFunction(value)) {
              value = _.bind(value, this, old);
            }
            this[key] = value;
          }
        }
        BaseView.__super__.constructor.call(this, options);
        this.promises.push(this.initHandlers(options.handlersIn));
      }

      BaseView.prototype.initialize = function(options) {
        var delegates, e, events, name, value, _results;
        events = options.events || {};
        if (_.isFunction(events)) {
          events = events.apply(this);
        }
        this.events = {};
        for (name in events) {
          value = events[name];
          if (this.feature.isFeatureEvent(name)) {
            this.feature.on(name, this.bindEventHandler(value));
          } else {
            e = this.wrapEvent(name, value);
            this.events[e.name] = e.handler;
          }
        }
        delegates = options.delegates || {};
        if (_.isFunction(delegates)) {
          delegates = delegates.apply(this);
        }
        _results = [];
        for (name in delegates) {
          value = delegates[name];
          e = this.wrapEvent(name, null);
          _results.push(this.events[e.name] = this.feature.delegateDomEvent(this, value, this.events[e.name]));
        }
        return _results;
      };

      BaseView.prototype.wrapEvent = function(name, handlerName) {
        var handler, n, parts;
        parts = name.replace(/^\s+/g, '').replace(/\s+$/, '').split(/\s+/);
        if (parts.length === 2) {
          if (parts[1].charAt(0) === '*') {
            n = parts[1].substring(0, parts[1].length - 1);
            n = this.genId(n);
            n = ' [id^="' + n + '"]';
            name = parts[0] + n;
          } else {
            name = parts[0] + ' #' + this.genId(parts[1]);
          }
        }
        if (!handlerName) {
          return {
            name: name
          };
        }
        if (!_.isFunction(handlerName)) {
          handler = this.bindEventHandler(handlerName);
        } else {
          handler = _.bind(handlerName, this);
        }
        return {
          name: name,
          handler: handler
        };
      };

      BaseView.prototype.bindEventHandler = function(name, namespace) {
        var _this = this;
        return function() {
          var args, handlers, method;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          handlers = namespace ? _this.eventHandlers[namespace] : _this.eventHandlers;
          if (!handlers) {
            error(_this, "no namespace named " + namespace);
          }
          method = handlers[name];
          if (!method) {
            error(_this, "no handler named " + name);
          }
          return method.apply(_this, args);
        };
      };

      BaseView.prototype.initHandlers = function(handler) {
        var deferred, path, _ref,
          _this = this;
        if ((_ref = this.eventHandlers) == null) {
          this.eventHandlers = {};
        }
        if (this.options.avoidLoadingHandlers === true) {
          deferred = $.Deferred();
          deferred.resolve({});
          return deferred.promise();
        }
        path = getPath(this.feature, 'handler', handler || this.baseName);
        return this.module.loadResource(path).done(function(handlers) {
          if (handlers == null) {
            handlers = {};
          }
          return _.extend(_this.eventHandlers, handlers);
        });
      };

      BaseView.prototype.template = function() {
        var name;
        name = this.options.template || this.baseName;
        return getPath(this.feature, 'template', name);
      };

      BaseView.prototype.getTemplateSelector = function() {
        var template;
        template = this.template;
        if (_.isFunction(template)) {
          template = template.call(this);
        }
        return this.module.resolveResoucePath(template + config.templateSuffix);
      };

      BaseView.prototype.mixinTemplateHelpers = function(target) {
        var data;
        data = BaseView.__super__.mixinTemplateHelpers.call(this, target);
        return _.extend(data, {
          settings: this.feature.module.getApplication().settings
        });
      };

      BaseView.prototype.afterRender = function() {
        if (_.isFunction(this.options.afterRender)) {
          return this.options.afterRender.call(this);
        }
      };

      BaseView.prototype.render = function(fn) {
        var deferred,
          _this = this;
        deferred = $.Deferred();
        $.when.apply($, this.promises).then(function() {
          return BaseView.__super__.render.apply(_this, arguments).done(function() {
            if (_.isFunction(fn)) {
              fn();
            }
            return deferred.resolve();
          });
        });
        return deferred.promise();
      };

      BaseView.prototype.genId = function(id) {
        return "" + this.cid + "-" + id;
      };

      BaseView.prototype.$ = function(selector) {
        return BaseView.__super__.$.call(this, '#' + this.genId(selector));
      };

      BaseView.prototype.$$ = function(selector) {
        return this.$el.find(selector);
      };

      BaseView.prototype.onRender = function() {
        var afterRenderDeferred, component, componentDeferred, components, evalAction, evalComponent, used, _i, _len, _ref,
          _this = this;
        used = {};
        this.$el.find('[id]').each(function(i, el) {
          var $el, id;
          $el = $(el);
          id = $el.attr('id');
          if (used[id] === true) {
            error(_this, "ID: " + id + " is used twice.");
          }
          used[id] = true;
          return $el.attr('id', _this.genId(id));
        });
        this.$el.find('[data-target]').each(function(i, el) {
          var $el, dt;
          $el = $(el);
          dt = $el.attr('data-target');
          if (dt.charAt(0) === '#') {
            dt = dt.substring(1);
          }
          return $el.attr('data-target', '#' + _this.genId(dt));
        });
        this.$el.find('[data-parent]').each(function(i, el) {
          var $el, dt;
          $el = $(el);
          dt = $el.attr('data-parent');
          if (dt.charAt(0) === '#') {
            dt = dt.substring(1);
          }
          return $el.attr('data-parent', '#' + _this.genId(dt));
        });
        this.$el.find('label[for]').each(function(i, el) {
          var $el, f;
          $el = $(el);
          f = $el.attr('for');
          return $el.attr('for', _this.genId(f));
        });
        components = [];
        evalComponent = function(view, $el, options) {
          var el, selector, type;
          type = options.type, selector = options.selector;
          delete options.type;
          delete options.selector;
          el = selector ? view.$(selector) : $el;
          return components.push(ComponentHandler.handle(type, el, options, this));
        };
        evalAction = function(view, $el, options) {
          var action, el, selector, _ref;
          action = options.action, selector = options.selector;
          delete options.action;
          delete options.selector;
          el = selector ? view.$(selector) : $el;
          return (_ref = el[action]) != null ? _ref.call(el, options) : void 0;
        };
        _ref = this.options.components || [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          component = _ref[_i];
          if (_.isFunction(component)) {
            component = component.call(this);
          }
          if (!component) {
            continue;
          }
          (component.type ? evalComponent : evalAction).call(this, this, this.$el, _.extend({}, component));
        }
        componentDeferred = $.Deferred();
        $.when.apply($, components).done(function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          _this.components = args;
          return componentDeferred.resolve(args);
        });
        afterRenderDeferred = this.afterRender.call(this);
        return $.when(componentDeferred, afterRenderDeferred).promise();
      };

      return BaseView;

    })(Marionette.ItemView);
    return BaseView;
  });

}).call(this);
