// Generated by CoffeeScript 1.4.0
(function() {
  var util,
    __slice = [].slice;

  util = {
    getBaseName: function(base) {
      var str;
      str = [];
      str.push("[" + base.baseName + "]");
      if (base.path) {
        str.push("[" + (base.path()) + "]");
      } else if (base.module && base.feature) {
        str.push("[" + (base.module.path(base.feature.baseName)) + "]");
      } else if (base.module) {
        str.push("[" + (base.module.path()) + "]");
      }
      return str.join(' under ');
    },
    log: function() {
      var base, messages;
      base = arguments[0], messages = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (!window.console) {
        return;
      }
      messages.unshift(util.getBaseName(base));
      return console.log.apply(console, messages);
    },
    error: function() {
      var base, messages;
      base = arguments[0], messages = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      messages.unshift(util.getBaseName(base));
      throw new Error(messages.join(' '));
    }
  };

  define(util);

}).call(this);
