// Generated by CoffeeScript 1.4.0
(function() {

  define(['underscore', 'coala/coala', 'jqueryui/accordion'], function(_, coala) {
    return coala.registerComponentHandler('accordion', (function() {}), function(el, options, view) {
      return el.accordion(options);
    });
  });

}).call(this);
