// Generated by CoffeeScript 1.4.0
(function() {

  define(['underscore', 'coala/coala', 'order!jqueryui/slider', 'order!jqueryui/datepicker', 'order!jqueryui/datepicker-zh-CN', 'order!coala/vendors/jquery/timepicker/jquery-ui-timepicker', 'order!coala/vendors/jquery/timepicker/jquery-ui-timepicker-zh-CN'], function(_, coala) {});

}).call(this);
