// Generated by CoffeeScript 1.4.0
(function() {

  define(['underscore', 'coala/coala', 'jqueryui/slider', 'jqueryui/datepicker', 'jqueryui/datepicker-zh-CN', 'coala/vendors/jquery/timepicker/jquery-ui-timepicker', 'coala/vendors/jquery/timepicker/jquery-ui-timepicker-zh-CN', 'coala/vendors/jquery/daterangepicker/date', 'coala/vendors/jquery/daterangepicker/daterangepicker'], function(_, coala) {});

}).call(this);
