// Generated by CoffeeScript 1.4.0
(function() {
  var _define;

  _define = function($) {
    var proto;
    proto = {
      on: function(event, func) {
        var parts;
        parts = event.split('.');
        if (parts.length === 2) {
          if (func != null) {
            this.unwrap().options[parts[0]]["on" + parts[1]] = func;
          } else {
            return this.unwrap().options[parts[0]]["on" + parts[1]];
          }
        }
      },
      off: function(event) {
        var parts;
        parts = event.split('.');
        if (parts.length === 2) {
          return this.unwrap().options[parts[0]]["on" + parts[1]] = null;
        }
      },
      unwrap: function() {
        if (this._layout != null) {
          return this._layout;
        } else {
          return this._layout = this.$el.data('layout');
        }
      }
    };
    return function(selector, options) {
      var $el, layout;
      $el = $(selector);
      layout = $el.data('zui.layout');
      if (layout == null) {
        layout = $el.layout(options);
        $el.data('zui.layout', $.extend({
          $el: $el
        }, proto));
      }
      return layout;
    };
  };

  if ((typeof define !== "undefined" && define !== null) && (define.amd != null)) {
    define(['jquery', 'jqueryui/draggable', 'jqueryui/effects/core', 'jqueryui/effects/slide', 'jqueryui/effects/drop', 'jqueryui/effects/scale', 'order!coala/vendors/jquery/layout/jquery.layout'], _define);
  } else {
    $.zui.layout = _define($);
  }

}).call(this);
