// Generated by CoffeeScript 1.4.0
(function() {

  define(['underscore', 'jquery', 'coala/coala'], function(_, $, coala) {
    return coala.registerComponentHandler('grid-picker', (function() {}), function(el, opt, view) {
      if (opt == null) {
        opt = {};
      }
    });
  });

}).call(this);
