// Generated by CoffeeScript 1.4.0
(function() {

  define(["underscore"], function(_) {
    return {
      avoidLoadingHandlers: true,
      extend: {
        templateHelpers: function() {
          var buttons, e, el, i, id;
          this.buttons = buttons = this.feature.startupOptions.buttons;
          this.eventHandlers || (this.eventHandlers = {});
          i = 0;
          while (i < buttons.length) {
            id = _.uniqueId("button");
            buttons[i].id = id;
            e = this.wrapEvent("click " + id, id);
            this.events[e.name] = e.handler;
            this.eventHandlers[id] = _(function(fn, b) {
              var result;
              if (this.$(id).hasClass('disabled')) {
                return;
              }
              result = fn.apply(this, [b]);
              if (result !== false) {
                return this.feature.modal.modal("hide");
              }
            }).bind(this, buttons[i].fn, buttons[i]);
            i++;
          }
          el = this.$el;
          this.$el = this.feature.dialogContainer;
          this.delegateEvents();
          this.$el = el;
          return {
            buttons: this.feature.startupOptions.buttons
          };
        }
      }
    };
  });

}).call(this);
