// Generated by CoffeeScript 1.4.0
(function() {

  define({
    regions: {
      operators: "operators",
      grid: "grid",
      completedOperators: "completedOperators",
      completedGrid: "completedGrid"
    },
    avoidLoadingHandlers: true
  });

}).call(this);
