// Generated by CoffeeScript 1.4.0
(function() {

  define({
    views: [
      {
        name: "operators",
        region: "operators"
      }, {
        name: "grid",
        region: "grid"
      }, {
        name: "completed-operators",
        region: "completedOperators"
      }, {
        name: "completed-grid",
        region: "completedGrid"
      }
    ],
    avoidLoadingModel: true
  });

}).call(this);
