// Generated by CoffeeScript 1.4.0
(function() {

  define({
    routes: {
      "start/*path": "hello"
    },
    hello: function(path) {
      return this.module.getApplication().applicationRoot.startFeature(path);
    }
  });

}).call(this);
