// Generated by CoffeeScript 1.4.0
(function() {

  define({
    layout: "one-region",
    views: [
      {
        name: "tree-picker-field",
        region: "main"
      }
    ],
    extend: {
      initRenderTarget: function() {
        return this.container = this.startupOptions.el;
      }
    },
    avoidLoadingModel: true
  });

}).call(this);
