// Generated by CoffeeScript 1.4.0
(function() {

  define({
    regions: {
      title: "modal-header",
      body: "modal-body",
      buttons: "modal-footer"
    },
    avoidLoadingHandlers: true
  });

}).call(this);
