// Generated by CoffeeScript 1.4.0
(function() {

  define({
    path: "completed",
    components: [
      {
        type: "grid",
        selector: "grid",
        pager: "pager",
        colModel: [
          {
            name: "id",
            label: "ID"
          }, {
            name: "name",
            label: "Name"
          }, {
            name: "createTime",
            label: "Create Time"
          }
        ]
      }
    ],
    avoidLoadingHandlers: true,
    avoidLoadingModel: true
  });

}).call(this);
