// Generated by CoffeeScript 1.4.0
(function() {

  define(["jquery", "underscore"], function($, _) {
    var handler;
    handler = function(app, featureName, id, data) {
      if (data.option && _.isString(data.option)) {
        data.option = eval('(' + data.option + ')');
      }
      app.startFeature(featureName, data);
      this.$$("li.active").removeClass("active");
      return this.$(id).parent().addClass("active");
    };
    return {
      model: "system/menuitems",
      avoidLoadingHandlers: true,
      extend: {
        serializeData: function() {
          var app, deferred, me;
          deferred = $.Deferred();
          me = this;
          app = me.feature.module.getApplication().applicationRoot;
          $.when(this.collection.fetch()).done(function() {
            me.collection.each(function(data, i) {
              var e, featureName, id;
              id = data.get("id");
              featureName = data.get("featurePath");
              e = void 0;
              me.eventHandlers[id] = _.bind(handler, me, app, featureName, id, data.toJSON());
              e = me.wrapEvent("click " + id, id);
              return me.events[e.name] = e.handler;
            });
            me.delegateEvents();
            return deferred.resolve({
              data: me.collection.toJSON()
            });
          });
          return deferred;
        }
      }
    };
  });

}).call(this);
