// Generated by CoffeeScript 1.4.0
(function() {

  define({
    events: {
      "click show-picker": "showPicker",
      "click remove-item": "removeItem"
    },
    components: [
      function() {
        var options;
        options = this.feature.startupOptions.grid || {};
        options.type = "grid";
        options.selector = "grid";
        return options;
      }
    ],
    extend: {
      templateHelpers: function() {
        return {
          fieldReadOnly: this.feature.startupOptions.readOnly
        };
      }
    }
  });

}).call(this);
